# -*- coding: utf-8 -*-
"""PANDAS LAB EXERCISE QUESTIONS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DBfns3icQEwKW9eVP31sonHYCr5O19jW
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/Salaries.csv')

df

df.head()

df.info()

"""what is the average BasePay?




"""

df['BasePay'].mean()

"""what is the highest amount of OvertimePay in the dataset?"""

df['OvertimePay'].max()

"""what is the job title of JOSEPH DRISCOLL? Note: Use all caps,otherwise you may get answer that doesn't match up"""

df[df['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle'	]

"""HOW MUCH DOES JOSEPH DRISCOLL MAKE(INCLUDING BENEFITS)?"""

df['TotalPayBenefits'] [df['EmployeeName']== 'JOSEPH DRISCOLL']

"""WHAT IS THE NAME OF THE HIGHEST PAID PERSON(INCLUDING BENEFITS)?"""

df[df['TotalPay'].max()==df['TotalPay']]

"""WHAT IS THE NAME OF THE LOWEST PAID PERSON(INCLUDING BENEFITS)?"""

df[df['TotalPay'].min()==df['TotalPay']]

"""WHAT WAS THE AVERAGE(MEAN) BasePay OF ALL EMPLOYEES PER YEAR? (2011-2014)"""

df.groupby('Year').mean()['BasePay']

"""HOW MANY UNIQUE JOB TITLES ARE THERE?"""

df['JobTitle'].nunique()

"""WHAT ARE THE TOP 5 MOST COMMON JOBS?"""

df['JobTitle'].value_counts().head()

"""HOW MANY JOB TITLES WERE REPRESENTED BY ONLY ONE PERSON IN 2013?(EG: JOB TITLE WITH ONLY ONE OCCURENCE IN 2013) """

(df[df['Year']==2013]['JobTitle'].value_counts()==1).sum()

"""HOW MANY PEOPLE HAVE THE WORD CHIEF IN THEIR JOB TITLE? """

df['JobTitle'].apply(lambda str:('chief' in str.lower())).sum()

def find_chief(job_title):    
    if 'chief' in job_title.lower().split():
        return True
    else:
        return False

df = pd.read_csv('Salaries.csv')

sum(df['JobTitle'].apply(lambda x: find_chief(x)))