# -*- coding: utf-8 -*-
"""CO1_Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YjlKv6BTw_EPCuNanNWyV4fuS2iWmd7u

**MATPLOTLIB:**
"""

import matplotlib.pyplot as plt
import numpy as np

x=np.linspace(0,5,11)
y=x**2

x

y

plt.plot(x,y,'g')#'r' is the color red
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.title('Title')
plt.show()

CREATE MULTIPLOTS ON SAME CANVAS::

#plt.subplot(nrows,ncolumns,plot_number)
plt.subplot(1,2,1)
plt.plot(x,y,'r--')
plt.subplot(1,2,2)
plt.plot(x,y,'b*--')

plt.subplot(1,3,1)
plt.plot(x,y,'r.-')
plt.subplot(1,3,2)
plt.plot(x,y,'b*-')
plt.subplot(1,3,3)
plt.plot(x,y,'g^-')

USING OBJECT ORIENTED:::

#create figure(empty canvas)
fig=plt.figure()
#add set of axes to figure
axes=fig.add_axes([0.3,0.7,0.6,0.5]) #left,bottom,width,height(range 0 to 1)
#plot on that set of axes
axes.plot(x,y,'b')
axes.set_xlabel('X Label')  # notice the use of set_ to begin methods
axes.set_ylabel('Y Label')
axes.set_title('Title')

#create blank canvas
fig=plt.figure()
axes1=fig.add_axes([0.7,0.6,0.9,0.9])
axes2=fig.add_axes([0.8,0.99,0.4,0.4])

#larger figure axes1
axes1.plot(x,y,'b')
axes1.set_xlabel('X Label') 
axes1.set_ylabel('Y Label')
axes1.set_title('Title')

#smaller figure axes 2
axes2.plot(y,x,'r')
axes2.set_xlabel('X Label') 
axes2.set_ylabel('Y Label')
axes2.set_title('Title')

SUBPLOTS::

fig,axes=plt.subplots()
axes.plot(x,y,'r')
axes.set_xlabel('x')
axes.set_ylabel('y')
axes.set_title('title');

fig,axes=plt.subplots(nrows=1,ncols=2)

for ax in axes:
  ax.plot(x,y,'b')
  ax.set_xlabel('x')
  ax.set_ylabel('y')
  ax.set_title('title')

fig

fig.tight_layout()

fig

fig=plt.figure(figsize=(8,4),dpi=100)

fig,axes=plt.subplots(figsize=(12,3))
axes.plot(x,y,'b')
axes.set_xlabel('x')
axes.set_ylabel('y')
axes.set_title('title')

SAVING FIGURES
fig.savefig("filename.png")
fig.savefig("filename.png",dpi=200)

LEGENDS::

fig=plt.figure()
ax=fig.add_axes([0,0,1,1])
ax.plot(x,x**2,label="x**2")
ax.plot(x,x**3,label="x**3")
ax.legend()

ax.legend(loc=1)  #upper right
ax.legend(loc=2)  #upper left
ax.legend(loc=3)  #lower left
ax.legend(loc=4)  #lower right
ax.legend(loc=0)  #let matplotlib decide the optimal location

#MATLAB style line color and style
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.plot(x,x**2,'b.-')  #blue line with dots
ax.plot(x,x**3,'g--')  #green dashed line